name: generate animation

on:
    # run automatically every 24 hours
    schedule:
        - cron: '0 */24 * * *'

    # allows to manually run the job at any time
    workflow_dispatch:

    # run on every push on the master branch
    push:
        branches:
            - snake

jobs:
    generate:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout snake branch
              uses: actions/checkout@v4
              with:
                  ref: snake
            
            # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
            - name: generate github-contribution-grid-snake.svg
              uses: Platane/snk/svg-only@v3
              with:
                  github_user_name: ${{ github.repository_owner }}
                  outputs: |
                      dist/github-contribution-grid-snake.svg
                      dist/github-contribution-grid-snake-dark.svg?palette=github-dark

            - name: Configure Git Author
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Commit and push changes
              run: |
                  git add dist/github-contribution-grid-snake.svg
                  git add dist/github-contribution-grid-snake-dark.svg
                  git diff-index --quiet HEAD || git commit -m "chore: Update snake SVG animation"
                  git push origin snake

            # push the content of <build_dir> to a branch
            # the content will be available as github page, or at 
            # https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>
            #- name: push github-contribution-grid-snake.svg to the output branch
            #  uses: crazy-max/ghaction-github-pages@v3.1.0
            #  with:
            #      target_branch: snake
            #      build_dir: dist
            #  env:
            #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create pull request
              uses: repo-sync/pull-request@v2
              with:
                  SOURCE_BRANCH: snake
                  DESTINATION_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  pr_title: 'Actualización de animación serpiente'
                  pr_body: 'Este PR actualiza las animaciones SVG de la serpiente con las últimas contribuciones.'
                  pr_draft: false
                  pr_allow_empty: false
                  pr_reviewers: ${{ github.repository_owner }}
                  pr_assignees: ${{ github.repository_owner }}
